name: unknown_studio
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.2

dependencies:
  flutter:
    sdk: flutter
  # shadcn_flutter:
  shadcn_flutter: # shadcnUI库_防止鸿蒙flutter报错
    git:
      url: https://github.com/qinshah/shadcn_flutter.git
  window_manager: ^0.5.1 # 窗口管理
  flutter_fancy_tree_view2: ^1.6.2 # 树形结构
  open_file: ^3.5.10 # 系统打开文件
  open_file_ohos: ^1.0.0 # 系统打开文件_鸿蒙
  webview_flutter: ^4.13.0 # web环境
  # webview_flutter: # web环境_鸿蒙
  #   git:
  #     url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
  #     path: "packages/webview_flutter/webview_flutter"
  file_selector: # 文件选择器_鸿蒙
    git:
      url: "https://gitcode.com/openharmony-tpc/flutter_packages.git"
      path: "packages/file_selector/file_selector"
      branch: "br_file_selector-v1.0.3_ohos"
  permission_handler: ^12.0.1 #TODO 鸿蒙
  file_icon: # 文件图标_新图标支持
    git:
      url: "https://github.com/qinshah/file-icon.git"
      path: "file_icon"
  mc_launch: # 启动mc
    git:
      url: "https://github.com/qinshah/mc_launch.git"
    # path: "Package/mc_launch"
dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
